/* eslint-disable @next/next/no-document-import-in-page */
// import Head from 'next/head';
// import { Html, Head, Main, NextScript } from 'next/document';

export default function CartPage() {
  return (
    // <Html>
    //   <Head>
    //     <title>Online Store Suka</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <body>
    //     <Main />
    <main>Cart Pages</main>
    //     <NextScript />
    //   </body>
    //   {/* <main>Cart Pages</main> */}
    // </Html>
  );
}
