name: online store next workflow
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get reposetory code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd my-app
          npm ci
      - name: Testing application
        run: |
          cd my-app
          npm run test
