name: online store next workflow
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app
    steps:
      - name: Get reposetory code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Testing application
        run: npm run test
